package enums;

public enum RequestType {
    REGISTER,
    LOGIN,
    EDIT_USER,
    GET_ADMIN,
    GET_DOCTOR_BY_USER,
    GET_DOCTOR,
    GETALL_DOCTORS,
    GETALL_PATIENTS,
    ADD_PATIENT,
    EDIT_PATIENT,
    DELETE_DOCTOR, EDIT_DOCTOR, ADD_DOCTOR, DELETE_PATIENT
}
