package enums;

public enum RequestType {
    REGISTER,
    LOGIN,
    EDIT_USER,
    GET_ADMIN,
    GET_DOCTOR,
    GET_USER,
    GET_VISIT,
    GETALL_DOCTORS,
    GETALL_PATIENTS,
    GETALL_USERS,
    GET_ALLVISITS,
    ADD_PATIENT,
    ADD_VISIT,
    EDIT_PATIENT,
    DELETE_PATIENT,
    EDIT_DOCTOR, ADD_DOCTOR, GET_DOCTOR_BY_USER

}
